# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d4ca00f1809e73d29070528920a3f8d807ee62bed6f8906ecf269f018df84905f1935f33d57086b824c0b0490f88bc09fcf3ee5e8c99c4979f5c9a51ad98f96

test:
  secret_key_base: d03849edd30e9aab2dd06e97fb9584c9192f416f79e9d0d88b2c9f057c5fb9d100ea28868412383a7b086710e024f05eb00865bf76e6423731c387ee4959f6b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
